### ISSUE TITLE
Add a code_of_conduct.md file to the repo.

### ISSUE THREAD

**Issue by CoachBirgit** [WordPress/DEIB-Issue-Tracker#2]
**User Story or Initial Idea:**  
As a contributor to the `#deib-working-group`, I want a clear code of conduct in the repository so that I understand the community's standards and values.

**Issue Summary:**  
The repository currently lacks a `code_of_conduct.md` file, which is essential to set the community's behavioral expectations.

**Background & Context (The Why):**  
A code of conduct ensures that all contributors adhere to a set of guidelines that promote a respectful and inclusive environment. It provides a reference point for acceptable behavior and procedures for addressing any issues. 

**Acceptance Criteria:**  
- [x] A comprehensive `code_of_conduct.md` file is added to the repository.
- [x] The file outlines the community's behavioral expectations and procedures for reporting violations.

**Proposed Steps or Tasks:**  
1. Research and review existing code of conduct templates.
2. Draft the `code_of_conduct.md` file tailored to the `#deib-working-group`.
3. Review and get feedback from the team.
4. Finalize and add the file to the repository.

**Dependencies or Blockers:**  
None identified.

**Additional Information:**  
Consider referencing the Contributor Covenant or other widely-accepted codes of conduct as a starting point.
- See as an example the [`code_of_conduct.md` from the Marketing Team repo](https://github.com/WordPress/Marketing-Team/blob/main/code_of_conduct.md)
- Link to the Community Code of Conduct: https://make.wordpress.org/handbook/community-code-of-conduct/

**Related Issues or Links:**  
None.

**Comment by ghost** [comment]
Is there any reason why we wouldn't use the Community code of conduct just like the marketing team is using?

**Comment by CoachBirgit** [comment]
No objections to forking the community code of conduct file from the marketing team. It needs the adjustments for this working group and then be added to the repo. @lada7042

**Comment by CoachBirgit** [comment]
done https://github.com/WordPress/DEIB-Issue-Tracker/blob/trunk/code_of_conduct.md
