### ISSUE TITLE
Create a CONTRIBUTING.md file and add it to the repo

### ISSUE THREAD

**Issue by CoachBirgit** [WordPress/DEIB-Issue-Tracker#3]
**User Story or Initial Idea:**  
As a potential contributor of the `#deib-working-group`, I want clear guidelines on how to contribute to the project so that I can effectively participate and collaborate.

**Issue Summary:**  
The repository needs a `CONTRIBUTING.md` file to guide contributors through the process of submitting pull requests, reporting issues, and participating in discussions.

**Background & Context (The Why):**  
Clear contribution guidelines ensure that all contributors follow a consistent process, making collaboration smoother and more efficient. It also helps in maintaining the quality and integrity of the project.

**Acceptance Criteria:**  
- [ ] A detailed `CONTRIBUTING.md` file is added to the repository.
- [ ] The file provides guidelines on submitting pull requests, reporting issues, and other contribution processes.

**Proposed Steps or Tasks:**  
1. Research best practices for contribution guidelines.
2. Draft the `CONTRIBUTING.md` file with clear steps and guidelines.
3. Review and gather feedback from the team.
4. Finalize and add the file to the repository.

**Dependencies or Blockers:**  
None identified.

**Additional Information:**  
Consider referencing contribution guidelines from other WordPress projects as inspiration.

**Related Issues or Links:**  
None.

**Comment by CoachBirgit** [comment]
I went ahead and created a Google Doc to collaborate on the content. 

[Working Doc for: CONTRIBUTING.md file and add it to the repo](https://docs.google.com/document/d/1BFV6X4kbdr3c8v28xXBb4k8QijyzTEacZl7nYj-y8kI/edit?usp=sharing) (Doc has commenting permissions)

If you need permissions to write on this document, please reach out to @CoachBirgit ([coachbirgit on Slack](https://wordpress.slack.com/team/U02RPUBD1)),

**Comment by TantienHime** [comment]
I would recommend two things (in addition to the above):

1. Intro docs from GitHub on how to add issues, projects, etc., so people don't get lost. If there is another place for this, then great, but thinking this is a good place for it.
2. Add a link in the main Readme file (if not already there) linking to this document.

**Comment by CoachBirgit** [comment]
Picked the content from https://wp-deib.org/contribute/ and put it to the [Google Doc. ](https://docs.google.com/document/d/1BFV6X4kbdr3c8v28xXBb4k8QijyzTEacZl7nYj-y8kI/edit?usp=sharing)
